# Generated by Django 3.1.3 on 2021-01-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40000)),
                ('urls', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40000)),
                ('last_name', models.CharField(max_length=40000)),
                ('email', models.EmailField(max_length=40000)),
                ('password1', models.CharField(max_length=40000)),
                ('password2', models.CharField(max_length=40000)),
            ],
        ),
    ]
