# Generated by Django 3.1.3 on 2021-01-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadfinderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='emails',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
