# Generated by Django 3.1.3 on 2021-01-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadfinderapp', '0006_auto_20210121_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password2',
        ),
    ]
