# Generated by Django 3.1.3 on 2021-01-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leadfinderapp', '0007_auto_20210121_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='llname',
        ),
    ]
